### ISSUE TITLE
[Q] SSE implementation details

### ISSUE THREAD

**Issue by genivia-inc** [lemire/validateutf8-experiments#1]
Thanks for posting this project based on your [paper](https://arxiv.org/pdf/2010.03090).

The paper's first part is very clear and easy to follow. Section 6.2 "Invalid 3-4 Byte Sequences"  leaves details out (it is only two paragraphs long). So I'm looking for clarification of Section 6.2 where you talk about using saturated subtraction and other possible tricks to validate two continuation bytes marked hex `80`. A UTF-8 hex `E` leading byte high nibble expects one hex `80` marker and a hex `F` leading byte high nibble expects two hex `80` markers. These are two and three bytes spaced apart from the leading UTF-8 byte.

The code base in this repo has a lot of boilerplate C++ code that abstracts away SIMD operations in favor of a higher level of abstraction, which makes the code obfuscated with respect to some details that one needs to trace through multiple source code files. I'm perhaps a bit too lazy to do all that and instead just wrote down a solution in a few hours.

I wrote the following SSE (SSE4.1 to be more specific) implementation listed below. For the Section 6.2 part I'm using two table lookups using a shuffle. I'm using `palignr` three times to get byte vectors shifted once, twice and three times to access up to three bytes ahead from the leading UTF-8 byte. Perhaps I'm not understanding the way you've approached this problem and if there is a faster way. Section 6.2 has no details and oversimplifies what needs to be done with some handwaving.

The code below runs nicely and fast. I tested this with "random" UTF-8 files. One small difference is that I flag a NUL byte as invalid:

```cpp
// check if UTF-8 from s up to e (exclusive)
bool isutf8(const char *s, const char *e)
{
  if (s <= e - 16)
  {
    //  ranges      UTF-8 encoding                                  nibbles
    //  U+0000      00000000                                        00x
    //  U+007f      01111111                                        7fx
    //
    //  U+0080      110.00010 10.000000                             c28 0
    //  U+07ff      110.11111 10.111111                             dfb f
    //
    //  U+0800      1110.0000 10.100000 10.000000                   e0a 080
    //  U+d7ff      1110.1101 10.011111 10.111111                   ed9 fbf
    //  U+e000      1110.1110 10.000000 10.000000                   ee8 080
    //  U+ffff      1110.1111 10.111111 10.111111                   efb fbf
    //
    //  U+010000    11110.000 10.010000 10.000000 10.000000         f09 00000
    //  U+10ffff    11110.100 10.001111 10.111111 10.111111         f48 fbfbf
    //
    //  UTF-8 error patterns:
    //   1:  (0~7) (0~f)     (8~b)
    //   2:  c     (0~1)     (0~f)
    //   3:  c     (2~f)     (0~7|c~f)
    //   4:  d     (0~f)     (0~7|c~f)
    //   5:  e     0         (0~7|8~9|c~f)
    //   6:  e     (1~8|e~f) (0~7|c~f)
    //   7:  e     d         (0~7|a~f)
    //   8:  f     0         (0~7|8)
    //   9:  f     (1~3)     (0~7|c~f)
    //  10:  f     4         (0~7|9~f)
    //
    //  combined error patterns and bit error assignment:
    //   1:        (0~7) (0~f) (8~b)          0
    //   2:        c     (0~1) (0~f)          1
    //   3+4+6+9:  (c~f) (0~f) (0~7|c~f)      2
    //   5:        e     0     (0~7|8~9|c~f)  3
    //   7:        e     d     (0~7|a~f)      4
    //   8:        f     0     (0~7|8)        5
    //  10:        f     4     (0~7|9~f)      6
    //  detect two continuation patterns with bit 7:
    //             (8~b) (0~f) (8~b)          7
    //
    //                 table index:   0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    //  previous high nibble table:  01 01 01 01 01 01 01 01 80 80 80 80 06 04 1c 64
    //  previous low nibble table:   ae 86 84 84 c4 84 84 84 85 85 85 85 85 95 85 85
    //  current high nibble table:   7e 7e 7e 7e 7e 7e 7e 7e ab cb d3 d3 5e 5e 5e 5e
    //
    const __m128i vpht = _mm_set_epi8(
    //  f    e    d    c    b    a    9    8    7    6    5    4    3    2    1    0
        0x64,0x1c,0x04,0x06,0x80,0x80,0x80,0x80,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01);
    const __m128i vplt = _mm_set_epi8(
    //  f    e    d    c    b    a    9    8    7    6    5    4    3    2    1    0
        0x85,0x85,0x95,0x85,0x85,0x85,0x85,0x85,0x84,0x84,0x84,0xc4,0x84,0x84,0x86,0xae);
    const __m128i vcht = _mm_set_epi8(
    //  f    e    d    c    b    a    9    8    7    6    5    4    3    2    1    0
        0x5e,0x5e,0x5e,0x5e,0xd3,0xd3,0xcb,0xab,0x7e,0x7e,0x7e,0x7e,0x7e,0x7e,0x7e,0x7e);
    const __m128i vqrt = _mm_set_epi8(
    //  f    e    d    c    b    a    9    8    7    6    5    4    3    2    1    0
        0xf0,0xe0,0xa0,0xa0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00);
    const __m128i vx0f = _mm_set1_epi8(0x0f);
    const __m128i vx7f = _mm_set1_epi8(0x7f);
    const __m128i v0 = _mm_setzero_si128();
    __m128i vc = v0;
    while (s <= e - 16)
    {
      __m128i vo = vc;
      vc = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s)); // current bytes
      __m128i vp = _mm_alignr_epi8(vc, vo, 15); // vc with previous byte
      __m128i vq = _mm_alignr_epi8(vc, vo, 14); // vc with two previous bytes
      __m128i vr = _mm_alignr_epi8(vc, vo, 13); // vc with three previous bytes
      __m128i vph = _mm_and_si128(_mm_srli_epi16(vp, 4), vx0f); // vp high nibbles
      __m128i vpl = _mm_and_si128(vp, vx0f);                    // vp low nibbles
      __m128i vch = _mm_and_si128(_mm_srli_epi16(vc, 4), vx0f); // vc high nibbles
      __m128i vt = _mm_shuffle_epi8(vpht, vph);
      vt = _mm_and_si128(vt, _mm_shuffle_epi8(vplt, vpl));
      vt = _mm_and_si128(vt, _mm_shuffle_epi8(vcht, vch));
      // if we have SSSE3 but not SSE4.1, then we can use this instead of the part below:
      // __m128i vm = _mm_add_epi8(_mm_and_si128(vt, vx7f), vx7f);
      // if (_mm_movemask_epi8(vm) != 0x0000)
      //   return false;
      // this requires SSE4.1:
      __m128i vm = _mm_and_si128(vt, vx7f);
      if (!_mm_testz_si128(vm, vm))
        return false;
      // if vq high nibble is 0~b then OK
      // if vq high nibble is c~d and vt bit 7 is 0 then OK
      // if vq high nibble is e~f and vt bit 7 is 1 then OK
      __m128i vqh = _mm_and_si128(_mm_srli_epi16(vq, 4), vx0f); // vq high nibbles
      __m128i vb = _mm_shuffle_epi8(vqrt, vqh);
      vm = _mm_xor_si128(_mm_and_si128(vb, vt), _mm_slli_epi16(vb, 1));
      // if vr high nibble is 0~b then OK
      // if vr high nibble is c~e and vt bit 7 is 0 then OK
      // if vr high nibble is f and vt bit 7 is 1 then OK
      __m128i vrh = _mm_and_si128(_mm_srli_epi16(vr, 4), vx0f); // vr high nibbles
      vb = _mm_shuffle_epi8(vqrt, vrh);
      vm = _mm_or_si128(vm, _mm_xor_si128(_mm_and_si128(_mm_slli_epi16(vb, 2), vt), _mm_slli_epi16(vb, 3)));
      if (_mm_movemask_epi8(vm) != 0x0000)
        return false;
      s += 16;
    }
    // do not end in the middle of a UTF-8 multibyte sequence, backtrack when necessary (this will terminate)
    while ((*--s & 0xc0) == 0x80)
      continue;
  }
  // ELIDED: scalar code goes here to validate UTF-8 from s up to e
}
```

In addition to this, I'm scanning the initial part of the input for ASCII (barring NUL), then check the remainder (if any) for valid UTF-8 which takes more time than an ASCII check.

_My question is, what SSE code do you use or propose to verify one- and two-byte markers for continuations? Also, do you see opportunities to speed this up further?_

Disclosure: I'm evaluating SIMD methods to speed up binary file detection in [ugrep](https://github.com/Genivia/ugrep). A binary file is a file that has NUL bytes (like GNU grep checks) but also when it has invalid UTF-8. The UTF-8 check does not need to be perfect, it just needs to detect "structurally invalid" UTF-8 (i.e. surrogates and overlongs are not bad if not detected as errors).

**Comment by lemire** [comment]
For production use, I recommend the [simdutf library](https://github.com/simdutf/simdutf). It is well tested and already in production use. It provides the UTF-8 validation routine at high speed on different systems.

Further, there are now many independent implementations.

- Google Fuchsia https://fuchsia-review.googlesource.com/c/fuchsia/+/695830/54/sdk/lib/utf-utils/internal/x86-ssse3.h
- [The PHP interpreter implementation ](https://github.com/php/php-src/blob/9147687b6d5c4491e1e19cb0d80ffabc479593ef/ext/mbstring/mbstring.c#L5266)


> Section 6.2 "Invalid 3-4 Byte Sequences" leaves details out (it is only two paragraphs long). (...) Section 6.2 has no details and oversimplifies what needs to be done with some handwaving.

Let us recap what the paper says...

<img width="605" alt="Screenshot 2024-08-21 at 10 58 53 AM" src="https://github.com/user-attachments/assets/61385a7e-ad31-41b7-9440-2129f2fa3eef">

The current repository (which is linked to from the paper) has code equivalent to...

```Cpp
  __m128i is_third_byte  = _mm_subs_epu8(vq,_mm_set1_epi8(0xe0u-0x80));
  __m128i is_fourth_byte = _mm_subs_epu8(vr,_mm_set1_epi8(0xf0u-0x80));
  __m128i must_be_cont = _mm_or_si128(is_third_byte, is_fourth_byte);
```

As you can see, it matches what the paper says.

That is, you need two subtraction and one bitwise OR (so 3 instructions).

There are different ways to do it. This is just a proposal. You can do it differently. Over time, I have seen 4 or 5 different ways to do it.

**Comment by lemire** [comment]
@genivia-inc You could just drop simdutf (simdutf.cpp and simdutf.h) in your project and you'd get the functionality you need and more...

https://github.com/simdutf/simdutf/releases/tag/v5.3.10

**Comment by genivia-inc** [comment]
Thanks for explaining. Fascinating stuff. I've updated my experimental code to compare performance and it runs faster. Nice.

An explanation is in order why I'm not using simdutf or other SIMD methods/libraries.

My dilemma is that I can't rely on the availability of SSE3, since the base ugrep version uses SSE2 for Intel CPUs, i.e. not SSE3 (or SSSE3) nor do I want to suddenly require SSE3 when it ran fast on SSE2 or have additional configure checks just for SSE3 to enable faster binary file checking (i.e. UTF-8 validation checking).

Of course, when AVX2 or AVX512BW is available then all of this will work fine, but it is unfortunate your method won't work with SSE2 but that is perfectly understandable.

So I wrote a faster SIMD UTF-8 validation check last week that uses "bit bashing". It works with SSE2 just fine and runs fast too (here compared to your table lookup method with the important change you proposed with saturated substitution):

| SIMD algorithm | time |
| --------------- | ---- |
| table lookup method SSE4.1 compiled with -mavx2 -O2 | 174ms |
| table lookup method SSE3 compiled with -msse3 -O2 | 205ms |
| bitbash method SSE4.1 version compiled with -mavx2 -O2 | 166ms |
| bitbash method SSE2 version compiled with -msse2 -O2 | 224ms |

Benchmark machine: MacOS 12.7.4 Intel quad core i7 2.9 GHz 16GB 2133 MHz LPDDR3
Benchmark file: enwik9 file size 1,000,000,000 mostly ASCII with some UTF-8

However, my proposed "bitbash" approach does not flag surrogates and accepts some overlongs in the 3 and 4 byte UTF-8 sequences. That is fine for quickly validating UTF-8 to check if the input is binary or resembles text.

"Bitbash" UTF-8 validation (with aforementioned limitation) in scalar code:
```cpp
bool isutf8(const char *s, const char *e)
{
  int8_t p = 0, q = 0, r = 0;
  while (s < e)
  {
    int8_t c = static_cast<int8_t>(*s++);
    if (!(c > 0 || (c > -63 && c < -11)))
      return false;
    if ((-(c < -64) ^ (p | q | r)) & 0x80)
      return false;
    r = (q & (q << 1));
    q = (p & (p << 1));
    p = (c & (c << 1));
  }
  return (p | q | r) & 0x80;
}
```
The SSE2 implementation with commentary (note that we can't use `palignr`):
```cpp
bool isutf8(const char *s, const char *e)
{
  if (s <= e - 16)
  {
    const __m128i vxc0 = _mm_set1_epi8(0xc0);
    const __m128i vxc1 = _mm_set1_epi8(0xc1);
    const __m128i vxf5 = _mm_set1_epi8(0xf5);
    const __m128i v0 = _mm_setzero_si128();
    __m128i vp = v0;
    __m128i vq = v0;
    __m128i vr = v0;
    while (s <= e - 16)
    {
      // step 1: check valid signed byte ranges
      //   c = s[i]
      //   if (!(c > 0 || (c > -63 && c < -11)))
      //     return false
      //
      __m128i vc = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
      __m128i vt = _mm_and_si128(_mm_cmpgt_epi8(vc, vxc1), _mm_cmplt_epi8(vc, vxf5));
      vt = _mm_or_si128(vt, _mm_cmplt_epi8(vc, vxc0));
      vt = _mm_or_si128(vt, _mm_cmpgt_epi8(vc, v0));
      if (_mm_movemask_epi8(vt) != 0xffff)
        return false;
      //
      //   step 2: check UTF-8 multi-byte sequences of 2, 3 and 4 bytes long
      //     if ((-(c < -64) ^ (p | q | r)) & 0x80)
      //       return false
      //     r = (q & (q << 1))
      //     q = (p & (p << 1))
      //     p = (c & (c << 1))
      //
      //   possible values of c after step 1 and subsequent values of p, q, r:
      //     c at 1st byte   p at 2nd byte   q at 3rd byte   r at 4th byte
      //       0xxxxxxx        0xxxxxxx        0xxxxxxx        0xxxxxxx
      //       10xxxxxx        00xxxxxx        00xxxxxx        00xxxxxx
      //       110xxxxx        100xxxxx        000xxxxx        000xxxxx
      //       1110xxxx        1100xxxx        1000xxxx        0000xxxx
      //       11110xxx        11100xxx        11000xxx        10000xxx
      //
      //   byte vectors vc, vp, vq, vr and previous values:
      //                             | c | c | c | c | ... | c |
      //                     | old p | p | p | p | p | ... | p |
      //             | old q | old q | q | q | q | q | ... | q |
      //     | old r | old r | old r | r | r | r | r | ... | r |
      //
      //   shift vectors vp, vq, vr to align to compute bitwise-or vp | vq | vr -> vt:
      //                 |     c |     c |     c | c | ... | c | = vc
      //                 | old p |     p |     p | p | ... | p |
      //                 | old q | old q |     q | q | ... | q |
      //                 | old r | old r | old r | r | ... | r |
      //                   -----   -----   -----   -   ---   -   or
      //                 |     t |     t |     t | t | ... | t | = vt
      //
      //   SSE2 code to perform r = (q & (q << 1)); q = (p & (p << 1)); p = (c & (c << 1));
      //   shift parts of the old vp, vq, vr and new vp, vq, vr in vt using psrldq and por
      //   then check if ((-(c < -64) ^ (p | q | r))) bit 7 is 0
      //
      vt = _mm_bsrli_si128(vp, 15);
      vp = _mm_and_si128(vc, _mm_add_epi8(vc, vc));
      vt = _mm_or_si128(vt, _mm_bsrli_si128(vq, 14));
      vq = _mm_and_si128(vp, _mm_add_epi8(vp, vp));
      vt = _mm_or_si128(vt, _mm_bsrli_si128(vr, 13));
      vr = _mm_and_si128(vq, _mm_add_epi8(vq, vq));
      vt = _mm_or_si128(vt, _mm_bslli_si128(vp, 1));
      vt = _mm_or_si128(vt, _mm_bslli_si128(vq, 2));
      vt = _mm_or_si128(vt, _mm_bslli_si128(vr, 3));
      vt = _mm_xor_si128(vt, _mm_cmplt_epi8(vc, vxc0));
      if (_mm_movemask_epi8(vt) != 0x0000)
        return false;
      s += 16;
    }
    // do not end in the middle of a UTF-8 multibyte sequence, backtrack when necessary (this will terminate)
    while ((*--s & 0xc0) == 0x80)
      continue;
  }
  // check remainder with scalar code
```
With SSE3/SSE4/AVX we can use `_mm_alignr_epi8 ` and no longer need the `_mm_bsrli_si128` and `_mm_bslli_si128`:
```cpp
    [...]
    const __m128i vxc0 = _mm_set1_epi8(0xc0);
    const __m128i vxc1 = _mm_set1_epi8(0xc1);
    const __m128i vxf5 = _mm_set1_epi8(0xf5);
    const __m128i v0 = _mm_setzero_si128();
    __m128i vp = v0;
    __m128i vq = v0;
    __m128i vr = v0;
    while (s <= e - 16)
    {
      __m128i vc = _mm_loadu_si128(reinterpret_cast<const __m128i*>(s));
      __m128i vt = _mm_and_si128(_mm_cmpgt_epi8(vc, vxc1), _mm_cmplt_epi8(vc, vxf5));
      vt = _mm_or_si128(vt, _mm_cmplt_epi8(vc, vxc0));
      vt = _mm_or_si128(vt, _mm_cmpgt_epi8(vc, v0));
      if (_mm_movemask_epi8(vt) != 0xffff)
        return false;
      __m128i vo = vp;
      vp = _mm_and_si128(vc, _mm_add_epi8(vc, vc));
      vt = _mm_alignr_epi8(vp, vo, 15);
      vo = vq;
      vq = _mm_and_si128(vp, _mm_add_epi8(vp, vp));
      vt = _mm_or_si128(vt, _mm_alignr_epi8(vq, vo, 14));
      vo = vr;
      vr = _mm_and_si128(vq, _mm_add_epi8(vq, vq));
      vt = _mm_or_si128(vt, _mm_alignr_epi8(vr, vo, 13));
      vt = _mm_xor_si128(vt, _mm_cmplt_epi8(vc, vxc0));
      if (_mm_movemask_epi8(vt) != 0x0000)
        return false;
      s += 16;
    }
    while ((*--s & 0xc0) == 0x80)
      continue;
```
This is what I have so far in my experimental setup. Perhaps the `_mm_movemask_epi8` can be combined into one in the code above if it speeds it up. I plan to experiment with this approach a bit more.

The "bitbash" UTF-8 validation in ARM NEON:
```cpp
  if (s <= e - 16)
  {
    const int8x16_t vxc0 = vdupq_n_s8(0xc0);
    const int8x16_t vxc1 = vdupq_n_s8(0xc1);
    const int8x16_t vxf5 = vdupq_n_s8(0xf5);
    const int8x16_t v0 = vdupq_n_s8(0);
    int8x16_t vp = v0;
    int8x16_t vq = v0;
    int8x16_t vr = v0;
    while (s <= e - 16)
    {
      int8x16_t vc = vld1q_s8(reinterpret_cast<const int8_t*>(s));
      int8x16_t vt = vandq_s8(vcgtq_s8(vc, vxc1), vcltq_s8(vc, vxf5));
      vt = vorrq_s8(vt, vcltq_s8(vc, vxc0));
      vt = vorrq_s8(vt, vcgtq_s8(vc, v0));
      int64x2_t vm = vreinterpretq_s64_s8(vt);
      if ((vgetq_lane_s64(vm, 0) & vgetq_lane_s64(vm, 1)) != -1LL)
        return false;
      int8x16_t vo = vp;
      vp = vandq_s8(vc, vshlq_n_s8(vc, 1));
      vt = vextq_s8(vo, vp, 15);
      vo = vq;
      vq = vandq_s8(vp, vshlq_n_s8(vp, 1));
      vt = vorrq_s8(vt, vextq_s8(vo, vq, 14));
      vo = vr;
      vr = vandq_s8(vq, vshlq_n_s8(vq, 1));
      vt = vorrq_s8(vt, vextq_s8(vo, vr, 13));
      vt = veorq_s8(vt, vcltq_s8(vc, vxc0));
      vm = vreinterpretq_s64_s8(vt);
      if (((vgetq_lane_s64(vm, 0) | vgetq_lane_s64(vm, 1)) & 0x8080808080808080LL) != 0)
        return false;
      s += 16;
    }
    while ((*--s & 0xc0) == 0x80)
      continue;
  }
```

**Comment by lemire** [comment]
> My dilemma is that I can't rely on the availability of SSE3, since the base ugrep version uses SSE2 for Intel CPUs, i.e. not SSE3 (or SSSE3) nor do I want to suddenly require SSE3 when it ran fast on SSE2 or have additional configure checks just for SSE3 to enable faster binary file checking (i.e. UTF-8 validation checking).

The simdutf library provides runtime dispatching. It does CPU feature detection.

Just drop `simdutf.cpp` in your project and you are done. It is magical.

**Do not build it** with system specific flags (e.g., `-march=native`).


This works today in Node.js in other systems. It is open source and carefully supported.

> Of course, when AVX2 or AVX512BW is available then all of this will work fine, but it is unfortunate your method won't work with SSE2 but that is perfectly understandable.

Recent versions of Windows 11, RedHat, SUSE and an increasing number of operating systems require x86-64-v2 (SSE3, SSSE3, SSE 4.1, SSE 4.2, POPCNT).

I submit to you that optimizing for pre-SSSE3 processors is not very useful, unless you are somehow targeting legacy systems. How many people use systems that they bought in 2008?

**Comment by genivia-inc** [comment]
> I submit to you that optimizing for pre-SSSE3 processors is not very useful, unless you are somehow targeting legacy systems. How many people use systems that they bought in 2008?

I was surprised to receive requests to have ugrep run on legacy systems including Windows 7 legacy systems that don't even support SSE2. It sounded silly, but it wasn't.

Allow me to explain that I'm using runtime dispatch in ugrep for SIMD matching with SSE2, AVX2, AVX512BW and NEON/AArch64. That SIMD code is a lot more complicated than UTF-8 validation, because the choice doesn't only depend on the CPU but also on the properties of the regex to match. So that's why I have these four SIMD classes specifically targeted. For 128 bit vectors SSE2 suffices. I wrote everything in ugrep from scratch, because its design is important to me and I can quickly add new things without bugs. Why from scratch? Well, I'm sometimes not very impressed with what is out there that I could use (I'm not talking about your work), but that I can design and write myself almost always better or come up with a better approach. I don't want to come across as "a know it all", but I spent 40 years in computer science starting with a math background and all the way up to becoming department chair before leaving academia (I'm running my own R&D shop now). Programming is a daily professional hobby of mine in addition to CS/math. Love these fields and don't feel it as work.

Hear me out on this one please. Adding UTF-8 validation should not require installing a library. The code is not complicated to implement (but coming up with interesting SIMD solutions sure is). Sorry to disappoint, but I'm happy using the simpler SSE2 bitbash code that runs fast enough (224ms with SSE2 versus 205ms table lookup with SSE3). There is only a 10% difference, while the SSE3 and AVX compiled version appears faster (or about the same). It's all fast enough and doesn't need another library or package installation or availability. It is not a selling point to have to install a software library to do something relatively simple when this simple thing is well documented. Library dependencies can break. I much rather have a reliable source documenting the algorithms and code that I am looking for, so I fully understand it and use it, while giving credit where credit is due.

**Comment by lemire** [comment]
Closing the issue.
